name: Build repo on ROS2 matrix

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      vcs_url:
        required: false
        type: string

jobs:
  build_on_noble:
    name: build_noble_${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [rolling]
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/${{ inputs.repo }}
          fetch-depth: 0
      - uses: ros-tooling/setup-ros@0.7.4
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - uses: ros-tooling/action-ros-ci@0.3.11
        with:
          target-ros2-distro: ${{ matrix.distro }}
          vcs-repo-file-url: ${{ inputs.vcs_url }}
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                    "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
                ]
              }
            }
  build_on_jammy:
    name: build_jammy_${{ matrix.distro }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        distro: [humble, iron]
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/${{ inputs.repo }}
          fetch-depth: 0
      - uses: ros-tooling/setup-ros@0.7.11
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - uses: ros-tooling/action-ros-ci@0.3.11
        with:
          target-ros2-distro: ${{ matrix.distro }}
          vcs-repo-file-url: ${{ inputs.vcs_url }}
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                    "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
                ]
              }
            }
  build_on_focal:
    name: build_focal_${{ matrix.distro }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # distro: [galactic, foxy]
        distro: [foxy]
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/${{ inputs.repo }}
          fetch-depth: 0
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ matrix.distro }}
          vcs-repo-file-url: ${{ inputs.vcs_url }}
          colcon-defaults: |
            {
              "build": {
                "cmake-args": [
                    "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
                ]
              }
            }
